[versions]
minecraft = "1.20"
fabric_loader = "0.14.22"

modmenu = "7.0.1"
fabric_api = "0.83.0+1.20"

cloth_config = "11.0.99"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

cloth_config = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth_config" }

[bundles]

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.4.5" }
